### ISSUE TITLE
VMAF-GUI doesnt generate output

### ISSUE THREAD

**Issue by Lukas-52** [Withenex/vmaf-gui#1]
Hi,
VMAF-GUI doesn't actually generate a output file. It only displays the one it comes with and if i delete that i can't write a new one.

It is creating both source and compressed .yuv files in its temp directory, so i don't think its a permission issue.

EDIT:
I am using the latest version 1.2.4 extracted from 7z File

**Comment by ThatNerdUKnow** [comment]
Sorry for taking so long to reply to this issue, but I can look into this after I get home from work today. I wonder if this may be an issue with the recent update of the bundled vmaf binary

**Comment by Lukas-52** [comment]
It would appear so, since Version 1.2.3 turned out to be working fine for me.

I case its of any use: At least according to task-manager it is doing something for about the time you would expect, it just doesn't write it into the log file.

**Comment by ThatNerdUKnow** [comment]
I've confirmed that the new bundled version of vmaf breaks the command line api. I'm currently working on getting it back in a working state

**Comment by ThatNerdUKnow** [comment]
I've removed the broken release from the releases page and I will work towards getting the new version of vmaf to work with the program. I will say however that the performance if the new vmaf is something to the order of 10fps so I don't know if it's the best path forward

**Comment by Lukas-52** [comment]
If the vmaf change logs are anything to go by the newer version are less easy to fool by psycho-visual optimizations and softening etc, they also are less likely to misjudge certain types of compression artifacts.

One issue i have for example is if you use footage that is a couple generations old (has been encoded before) as source, sour vmaf score will always be significantly lower than expected (~84). Even if the "compressed" video was encoded as something like crf 2 in AV1 at very slow preset (in my case that produces a file three times the size of the original).

If i plug the same files into the ffmpeg+vmaf manually i get an avg. score of ~98 with even the 10 worst frames above 96.

**Comment by ThatNerdUKnow** [comment]
I have noticed that vmaf tends to be rather optimistic in it's scoring. For example if i were to reencode a source video with a crf value of something ridiculously high it still gives me a score in the high 90's. I am also considering scrapping this project in favor of building an electron version since it's easier to make changes to the UI as needed. Also it would be better to use libvmaf or it's python equivalent to interact with the vmaf model rather than using sdtin as SDK's tend to have a more stable interface. For now i'm going to keep working on getting vmaf-gui to work with the new bundled vmaf and then probably work on it's successor

**Comment by ShortyCM** [comment]
High 90s no matter the CRF?  Are you sure you're not making an error somewhere?  It's been so long since I ran this test that I no longer recall for sure what the source was, but it was 1080p testing with x264/x265 medium with and without -grain at all the whole-number CRF values.  I think it may have been chapter 2 of The Godfather, though.  These figures were generated via the command line tools.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link id=Main-File rel=Main-File href="file:///C:\temp\msohtml1\01\clip.htm">
<link rel=Edit-Time-Data href="file:///C:\temp\msohtml1\01\clip_editdata.mso">
<link rel=OLE-Object-Data href="file:///C:\temp\msohtml1\01\clip_oledata.mso">
<style>

</style>
</head>

<body link=blue vlink=purple>



CRF | x264 | x264 grain | x265 | x265 grain
-- | -- | -- | -- | --
0 | 100.000000 | 100.000000 | 100.000000 | 100.000000
1 | 100.000000 | 100.000000 | 100.000000 | 100.000000
2 | 100.000000 | 100.000000 | 100.000000 | 100.000000
3 | 100.000000 | 100.000000 | 100.000000 | 100.000000
4 | 100.000000 | 99.989868 | 100.000000 | 100.000000
5 | 100.000000 | 99.720329 | 100.000000 | 100.000000
6 | 100.000000 | 99.496844 | 100.000000 | 100.000000
7 | 100.000000 | 99.158023 | 100.000000 | 100.000000
8 | 99.899623 | 99.033589 | 100.000000 | 100.000000
9 | 99.782708 | 98.969035 | 100.000000 | 100.000000
10 | 99.640328 | 98.993404 | 99.927971 | 100.000000
11 | 99.507034 | 99.001283 | 99.869437 | 99.917924
12 | 99.350654 | 98.935628 | 99.704195 | 99.901338
13 | 99.114955 | 98.861030 | 99.542476 | 99.774489
14 | 98.884312 | 98.716098 | 99.352009 | 99.652184
15 | 98.564232 | 98.622360 | 99.176496 | 99.533680
16 | 98.211461 | 98.494175 | 99.044633 | 99.412040
17 | 97.851815 | 98.272962 | 98.990435 | 99.130943
18 | 97.496458 | 97.981491 | 98.701649 | 99.040868
19 | 96.937652 | 97.573321 | 98.294597 | 98.851239
20 | 96.597624 | 97.250969 | 97.863168 | 98.683917
21 | 96.020399 | 96.735902 | 97.351814 | 98.331230
22 | 95.301659 | 96.174947 | 96.894444 | 97.965302
23 | 94.740335 | 95.649054 | 96.406187 | 97.499484
24 | 93.958087 | 95.165422 | 95.786474 | 97.133890
25 | 93.050461 | 94.549260 | 95.318585 | 96.650238
26 | 92.362532 | 93.934927 | 94.750263 | 96.056859
27 | 91.178412 | 93.169392 | 94.090129 | 95.481846
28 | 90.451262 | 92.192773 | 93.403392 | 94.896866
29 | 89.498197 | 91.231897 | 92.405221 | 94.410310
30 | 88.203395 | 90.295945 | 91.880103 | 93.693983
31 | 87.077671 | 89.127596 | 90.824786 | 92.574535
32 | 85.605483 | 87.858679 | 89.799903 | 92.219984
33 | 83.985719 | 86.605922 | 88.527542 | 90.856538
34 | 82.497360 | 85.203880 | 87.138368 | 89.897476
35 | 79.914573 | 83.389262 | 86.123407 | 88.604589
36 | 78.280810 | 81.589729 | 84.677629 | 87.541128
37 | 75.104820 | 79.139870 | 82.730542 | 85.954092
38 | 73.364936 | 77.461081 | 81.219523 | 84.953247
39 | 70.818646 | 75.407227 | 79.121316 | 83.301501
40 | 67.744040 | 72.794971 | 76.254855 | 81.101729
41 | 65.433204 | 69.646748 | 74.629494 | 79.262625
42 | 62.789880 | 67.520849 | 71.742621 | 77.358034
43 | 60.311440 | 64.897782 | 69.146455 | 74.980233
44 | 56.789501 | 62.228435 | 66.038845 | 73.284053
45 | 53.197175 | 58.097983 | 63.833662 | 69.473320
46 | 51.472389 | 54.752848 | 60.637392 | 66.103568
47 | 49.723677 | 53.905297 | 58.110930 | 64.490310
48 | 48.135977 | 50.661742 | 55.094817 | 61.425894
49 | 48.126504 | 48.490351 | 51.250790 | 58.536170
50 | 47.687273 | 47.441768 | 49.185574 | 54.141408
51 | 46.074157 | 47.075156 | 48.011295 | 50.178340
21   ultrafast |   | 95.639820 | 97.891255
21   superfast |   | 96.243220 | 98.331255
21 veryfast |   | 97.249184 | 98.379432
21 faster |   |   | 97.249184 | 98.379432
21 fast |   |   | 97.249184 | 98.379432
21 slow |   |   | 97.317043 | 98.809481
21 slower |   |   | 97.276173 | 98.780680
21 very   slow |   | 97.276173 | 98.780680
21 placebo |   | 97.272983 | 98.774259
18 ultrafast | 98.620665 | 97.090850 |   |  
18 superfast | 99.037035 | 98.785543 |   |  
18 veryfast | 96.901821 | 98.236854 |   |  
18 faster | 97.259326 | 97.948685 |   |  
18 fast | 97.497227 | 97.949596 |   |  
18 slow | 97.671039 | 98.644395 |   |  
18 slower | 97.352829 | 98.552602 |   |  
18 very slow | 97.218443 | 98.169597 |   |  
18 placebo | 97.196007 | 98.220520 |   |  



</body>

</html>

**Comment by ThatNerdUKnow** [comment]
I totally agree with you. I wonder if it's a problem with the way i'm building the command line arguments or the arguments that i'm setting by default here. I'm gonna go back to command line only just to seperate this issue from anything i'm doing in the ui. Just for a sanity check

**Comment by Lukas-52** [comment]
To add what little i have:
I did some testing with fairly low CRF values using AV1 with -cpu-used 1 and a total of 2 tiles. The file is Talking head type footage recorded using optimized green screen (so no noise in the green parts) and is therefore very easy to encode
![GitVMAF](https://user-images.githubusercontent.com/94807978/149075117-01eb4023-269a-4218-93e7-7ab2452f3b59.PNG)
Mind the percentiles, since i don't give much about average when the minimums are terrible.

This would sort of proof ShortyCMs data, since relatively speaking his lower values are also pretty close together and fairly high up.

**Comment by ThatNerdUKnow** [comment]
I've been sick for the past few days so I'm going to work on this on the weekend and hopefully I can get a release out that we're happy with
