### ISSUE TITLE
Huge .y4m file size (~20–30 ✕ original)

### ISSUE THREAD

**Issue by galantra** [Withenex/vmaf-gui#14]
# The issue

source.y4m size: 284.3 G (305 255 244 908 bytes)
![image](https://github.com/ThatNerdUKnow/vmaf-gui/assets/52420923/52b2d565-e31b-41a8-a928-2f3dc8ea94f3)

compressed.y4m size: 88.5 G (94 981 849 088 bytes)
![image](https://github.com/ThatNerdUKnow/vmaf-gui/assets/52420923/51557862-ce59-4fa4-99c2-c4ffd15c2214)

Source size: 14.7 G (15 749 803 095 bytes)

Compressed size: 3.4 G (3 670 213 684 bytes)

# Additional info

Eventually, vmafgui exits with 

```
---------------------------
There was a problem with VMAF
---------------------------
Error reading YUV frame data.



problem reading pictures

problem flushing context


---------------------------
OK   
---------------------------

```

the .y4m files are not deleted.

**Comment by ThatNerdUKnow** [comment]
This is a known problem, y4m files are basically decompressed video files which are much bigger than regular compressed video. It's necessary for me to turn video into .y4m format before sending it to the vmaf cli. I'm currently working on rewriting this application to use libvmaf directly instead of via the CLI interface which should keep only the current frames under consideration in memory which should preserve disk space/memory

**Comment by ThatNerdUKnow** [comment]
If I had to take a guess, I'd say it's likely that you ran out of disk space writing that second y4m file. because it's decompressed video the file size should be roughly the same assuming the resolution and framerate match between the two videos
